# Generated by Django 5.2 on 2025-11-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_usuario_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
