# Generated by Django 5.2 on 2025-11-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_solicitud_delete_solicitudes_vehiculo_vendedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='km',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
